authorization {
  users = [
    {
      user: "app"
      password: "secret"
      permissions: {
        publish: { allow: [">"] }
        subscribe: { allow: [">"] }
      }
    }
    {
      user: "restricted"
      password: "secret"
      permissions: {
        publish: { allow: ["allowed.>"] }
        subscribe: { allow: ["allowed.>", "_INBOX.>"] }
      }
    }
  ]
}
